from setuptools import setup

setup(
    name='tweepysent',
    version='1.0',
    packages=['venv.Lib.distutils', 'venv.Lib.encodings', 'venv.Lib.importlib', 'venv.Lib.collections',
              'venv.Lib.site-packages.PIL', 'venv.Lib.site-packages.pip', 'venv.Lib.site-packages.pip._vendor',
              'venv.Lib.site-packages.pip._vendor.idna', 'venv.Lib.site-packages.pip._vendor.pep517',
              'venv.Lib.site-packages.pip._vendor.pytoml', 'venv.Lib.site-packages.pip._vendor.certifi',
              'venv.Lib.site-packages.pip._vendor.chardet', 'venv.Lib.site-packages.pip._vendor.chardet.cli',
              'venv.Lib.site-packages.pip._vendor.distlib', 'venv.Lib.site-packages.pip._vendor.distlib._backport',
              'venv.Lib.site-packages.pip._vendor.msgpack', 'venv.Lib.site-packages.pip._vendor.urllib3',
              'venv.Lib.site-packages.pip._vendor.urllib3.util', 'venv.Lib.site-packages.pip._vendor.urllib3.contrib',
              'venv.Lib.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.Lib.site-packages.pip._vendor.urllib3.packages',
              'venv.Lib.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.Lib.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.pip._vendor.colorama', 'venv.Lib.site-packages.pip._vendor.html5lib',
              'venv.Lib.site-packages.pip._vendor.html5lib._trie',
              'venv.Lib.site-packages.pip._vendor.html5lib.filters',
              'venv.Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.pip._vendor.html5lib.treebuilders', 'venv.Lib.site-packages.pip._vendor.lockfile',
              'venv.Lib.site-packages.pip._vendor.progress', 'venv.Lib.site-packages.pip._vendor.requests',
              'venv.Lib.site-packages.pip._vendor.packaging', 'venv.Lib.site-packages.pip._vendor.cachecontrol',
              'venv.Lib.site-packages.pip._vendor.cachecontrol.caches',
              'venv.Lib.site-packages.pip._vendor.webencodings', 'venv.Lib.site-packages.pip._vendor.pkg_resources',
              'venv.Lib.site-packages.pip._internal', 'venv.Lib.site-packages.pip._internal.cli',
              'venv.Lib.site-packages.pip._internal.req', 'venv.Lib.site-packages.pip._internal.vcs',
              'venv.Lib.site-packages.pip._internal.utils', 'venv.Lib.site-packages.pip._internal.models',
              'venv.Lib.site-packages.pip._internal.commands', 'venv.Lib.site-packages.pip._internal.operations',
              'venv.Lib.site-packages.rsa', 'venv.Lib.site-packages.grpc', 'venv.Lib.site-packages.grpc.beta',
              'venv.Lib.site-packages.grpc._cython', 'venv.Lib.site-packages.grpc._cython._cygrpc',
              'venv.Lib.site-packages.grpc.framework', 'venv.Lib.site-packages.grpc.framework.common',
              'venv.Lib.site-packages.grpc.framework.foundation', 'venv.Lib.site-packages.grpc.framework.interfaces',
              'venv.Lib.site-packages.grpc.framework.interfaces.base',
              'venv.Lib.site-packages.grpc.framework.interfaces.face', 'venv.Lib.site-packages.grpc.experimental',
              'venv.Lib.site-packages.idna', 'venv.Lib.site-packages.nltk', 'venv.Lib.site-packages.nltk.lm',
              'venv.Lib.site-packages.nltk.app', 'venv.Lib.site-packages.nltk.ccg', 'venv.Lib.site-packages.nltk.sem',
              'venv.Lib.site-packages.nltk.tag', 'venv.Lib.site-packages.nltk.tbl', 'venv.Lib.site-packages.nltk.chat',
              'venv.Lib.site-packages.nltk.draw', 'venv.Lib.site-packages.nltk.misc',
              'venv.Lib.site-packages.nltk.stem', 'venv.Lib.site-packages.nltk.test',
              'venv.Lib.site-packages.nltk.test.unit', 'venv.Lib.site-packages.nltk.test.unit.lm',
              'venv.Lib.site-packages.nltk.test.unit.translate', 'venv.Lib.site-packages.nltk.chunk',
              'venv.Lib.site-packages.nltk.parse', 'venv.Lib.site-packages.nltk.corpus',
              'venv.Lib.site-packages.nltk.corpus.reader', 'venv.Lib.site-packages.nltk.cluster',
              'venv.Lib.site-packages.nltk.metrics', 'venv.Lib.site-packages.nltk.twitter',
              'venv.Lib.site-packages.nltk.classify', 'venv.Lib.site-packages.nltk.tokenize',
              'venv.Lib.site-packages.nltk.inference', 'venv.Lib.site-packages.nltk.sentiment',
              'venv.Lib.site-packages.nltk.translate', 'venv.Lib.site-packages.pytz', 'venv.Lib.site-packages.numpy',
              'venv.Lib.site-packages.numpy.ma', 'venv.Lib.site-packages.numpy.ma.tests',
              'venv.Lib.site-packages.numpy.doc', 'venv.Lib.site-packages.numpy.fft',
              'venv.Lib.site-packages.numpy.fft.tests', 'venv.Lib.site-packages.numpy.lib',
              'venv.Lib.site-packages.numpy.lib.tests', 'venv.Lib.site-packages.numpy.core',
              'venv.Lib.site-packages.numpy.core.tests', 'venv.Lib.site-packages.numpy.f2py',
              'venv.Lib.site-packages.numpy.f2py.tests', 'venv.Lib.site-packages.numpy.tests',
              'venv.Lib.site-packages.numpy.compat', 'venv.Lib.site-packages.numpy.compat.tests',
              'venv.Lib.site-packages.numpy.linalg', 'venv.Lib.site-packages.numpy.linalg.tests',
              'venv.Lib.site-packages.numpy.random', 'venv.Lib.site-packages.numpy.random.tests',
              'venv.Lib.site-packages.numpy.testing', 'venv.Lib.site-packages.numpy.testing.tests',
              'venv.Lib.site-packages.numpy.testing._private', 'venv.Lib.site-packages.numpy.distutils',
              'venv.Lib.site-packages.numpy.distutils.tests', 'venv.Lib.site-packages.numpy.distutils.command',
              'venv.Lib.site-packages.numpy.distutils.fcompiler', 'venv.Lib.site-packages.numpy.matrixlib',
              'venv.Lib.site-packages.numpy.matrixlib.tests', 'venv.Lib.site-packages.numpy.polynomial',
              'venv.Lib.site-packages.numpy.polynomial.tests', 'venv.Lib.site-packages.scipy',
              'venv.Lib.site-packages.scipy.io', 'venv.Lib.site-packages.scipy.io.arff',
              'venv.Lib.site-packages.scipy.io.arff.tests', 'venv.Lib.site-packages.scipy.io.tests',
              'venv.Lib.site-packages.scipy.io.matlab', 'venv.Lib.site-packages.scipy.io.matlab.tests',
              'venv.Lib.site-packages.scipy.io.harwell_boeing', 'venv.Lib.site-packages.scipy.io.harwell_boeing.tests',
              'venv.Lib.site-packages.scipy.odr', 'venv.Lib.site-packages.scipy.odr.tests',
              'venv.Lib.site-packages.scipy._lib', 'venv.Lib.site-packages.scipy._lib.tests',
              'venv.Lib.site-packages.scipy.misc', 'venv.Lib.site-packages.scipy.misc.tests',
              'venv.Lib.site-packages.scipy.stats', 'venv.Lib.site-packages.scipy.stats.tests',
              'venv.Lib.site-packages.scipy.linalg', 'venv.Lib.site-packages.scipy.linalg.tests',
              'venv.Lib.site-packages.scipy.signal', 'venv.Lib.site-packages.scipy.signal.tests',
              'venv.Lib.site-packages.scipy.signal.windows', 'venv.Lib.site-packages.scipy.sparse',
              'venv.Lib.site-packages.scipy.sparse.tests', 'venv.Lib.site-packages.scipy.sparse.linalg',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen.arpack',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen.arpack.tests',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen.lobpcg',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen.lobpcg.tests',
              'venv.Lib.site-packages.scipy.sparse.linalg.tests', 'venv.Lib.site-packages.scipy.sparse.linalg.dsolve',
              'venv.Lib.site-packages.scipy.sparse.linalg.dsolve.tests',
              'venv.Lib.site-packages.scipy.sparse.linalg.isolve',
              'venv.Lib.site-packages.scipy.sparse.linalg.isolve.tests', 'venv.Lib.site-packages.scipy.sparse.csgraph',
              'venv.Lib.site-packages.scipy.sparse.csgraph.tests', 'venv.Lib.site-packages.scipy.cluster',
              'venv.Lib.site-packages.scipy.cluster.tests', 'venv.Lib.site-packages.scipy.fftpack',
              'venv.Lib.site-packages.scipy.fftpack.tests', 'venv.Lib.site-packages.scipy.ndimage',
              'venv.Lib.site-packages.scipy.ndimage.tests', 'venv.Lib.site-packages.scipy.spatial',
              'venv.Lib.site-packages.scipy.spatial.tests', 'venv.Lib.site-packages.scipy.spatial.transform',
              'venv.Lib.site-packages.scipy.spatial.transform.tests', 'venv.Lib.site-packages.scipy.special',
              'venv.Lib.site-packages.scipy.special.tests', 'venv.Lib.site-packages.scipy.special._precompute',
              'venv.Lib.site-packages.scipy.optimize', 'venv.Lib.site-packages.scipy.optimize._lsq',
              'venv.Lib.site-packages.scipy.optimize.tests', 'venv.Lib.site-packages.scipy.optimize._trlib',
              'venv.Lib.site-packages.scipy.optimize._shgo_lib',
              'venv.Lib.site-packages.scipy.optimize._trustregion_constr',
              'venv.Lib.site-packages.scipy.optimize._trustregion_constr.tests',
              'venv.Lib.site-packages.scipy.constants', 'venv.Lib.site-packages.scipy.constants.tests',
              'venv.Lib.site-packages.scipy.integrate', 'venv.Lib.site-packages.scipy.integrate._ivp',
              'venv.Lib.site-packages.scipy.integrate.tests', 'venv.Lib.site-packages.scipy.interpolate',
              'venv.Lib.site-packages.scipy.interpolate.tests', 'venv.Lib.site-packages.scipy._build_utils',
              'venv.Lib.site-packages.tests', 'venv.Lib.site-packages.wheel', 'venv.Lib.site-packages.wheel.cli',
              'venv.Lib.site-packages.google.api', 'venv.Lib.site-packages.google.rpc',
              'venv.Lib.site-packages.google.auth', 'venv.Lib.site-packages.google.auth.crypt',
              'venv.Lib.site-packages.google.auth.transport', 'venv.Lib.site-packages.google.auth.compute_engine',
              'venv.Lib.site-packages.google.type', 'venv.Lib.site-packages.google.cloud.language_v1',
              'venv.Lib.site-packages.google.cloud.language_v1.gapic',
              'venv.Lib.site-packages.google.cloud.language_v1.gapic.transports',
              'venv.Lib.site-packages.google.cloud.language_v1.proto',
              'venv.Lib.site-packages.google.cloud.translate_v2',
              'venv.Lib.site-packages.google.cloud.language_v1beta2',
              'venv.Lib.site-packages.google.cloud.language_v1beta2.gapic',
              'venv.Lib.site-packages.google.cloud.language_v1beta2.gapic.transports',
              'venv.Lib.site-packages.google.cloud.language_v1beta2.proto',
              'venv.Lib.site-packages.google.cloud.translate_v3beta1',
              'venv.Lib.site-packages.google.cloud.translate_v3beta1.gapic',
              'venv.Lib.site-packages.google.cloud.translate_v3beta1.gapic.transports',
              'venv.Lib.site-packages.google.cloud.translate_v3beta1.proto', 'venv.Lib.site-packages.google.oauth2',
              'venv.Lib.site-packages.google.logging.type', 'venv.Lib.site-packages.google.api_core',
              'venv.Lib.site-packages.google.api_core.future', 'venv.Lib.site-packages.google.api_core.gapic_v1',
              'venv.Lib.site-packages.google.api_core.operations_v1', 'venv.Lib.site-packages.google.protobuf',
              'venv.Lib.site-packages.google.protobuf.util', 'venv.Lib.site-packages.google.protobuf.pyext',
              'venv.Lib.site-packages.google.protobuf.compiler', 'venv.Lib.site-packages.google.protobuf.internal',
              'venv.Lib.site-packages.google.protobuf.internal.import_test_package',
              'venv.Lib.site-packages.google.longrunning', 'venv.Lib.site-packages.pandas',
              'venv.Lib.site-packages.pandas.io', 'venv.Lib.site-packages.pandas.io.sas',
              'venv.Lib.site-packages.pandas.io.json', 'venv.Lib.site-packages.pandas.io.formats',
              'venv.Lib.site-packages.pandas.io.msgpack', 'venv.Lib.site-packages.pandas.io.clipboard',
              'venv.Lib.site-packages.pandas.api', 'venv.Lib.site-packages.pandas.api.types',
              'venv.Lib.site-packages.pandas.api.extensions', 'venv.Lib.site-packages.pandas.core',
              'venv.Lib.site-packages.pandas.core.util', 'venv.Lib.site-packages.pandas.core.tools',
              'venv.Lib.site-packages.pandas.core.arrays', 'venv.Lib.site-packages.pandas.core.dtypes',
              'venv.Lib.site-packages.pandas.core.sparse', 'venv.Lib.site-packages.pandas.core.groupby',
              'venv.Lib.site-packages.pandas.core.indexes', 'venv.Lib.site-packages.pandas.core.reshape',
              'venv.Lib.site-packages.pandas.core.internals', 'venv.Lib.site-packages.pandas.core.computation',
              'venv.Lib.site-packages.pandas.util', 'venv.Lib.site-packages.pandas._libs',
              'venv.Lib.site-packages.pandas._libs.tslibs', 'venv.Lib.site-packages.pandas.tests',
              'venv.Lib.site-packages.pandas.tests.io', 'venv.Lib.site-packages.pandas.tests.io.sas',
              'venv.Lib.site-packages.pandas.tests.io.json', 'venv.Lib.site-packages.pandas.tests.io.parser',
              'venv.Lib.site-packages.pandas.tests.io.formats', 'venv.Lib.site-packages.pandas.tests.io.msgpack',
              'venv.Lib.site-packages.pandas.tests.api', 'venv.Lib.site-packages.pandas.tests.util',
              'venv.Lib.site-packages.pandas.tests.frame', 'venv.Lib.site-packages.pandas.tests.tools',
              'venv.Lib.site-packages.pandas.tests.arrays', 'venv.Lib.site-packages.pandas.tests.arrays.sparse',
              'venv.Lib.site-packages.pandas.tests.arrays.interval',
              'venv.Lib.site-packages.pandas.tests.arrays.categorical', 'venv.Lib.site-packages.pandas.tests.dtypes',
              'venv.Lib.site-packages.pandas.tests.dtypes.cast', 'venv.Lib.site-packages.pandas.tests.scalar',
              'venv.Lib.site-packages.pandas.tests.scalar.period',
              'venv.Lib.site-packages.pandas.tests.scalar.interval',
              'venv.Lib.site-packages.pandas.tests.scalar.timedelta',
              'venv.Lib.site-packages.pandas.tests.scalar.timestamp', 'venv.Lib.site-packages.pandas.tests.series',
              'venv.Lib.site-packages.pandas.tests.series.indexing', 'venv.Lib.site-packages.pandas.tests.sparse',
              'venv.Lib.site-packages.pandas.tests.sparse.frame', 'venv.Lib.site-packages.pandas.tests.sparse.series',
              'venv.Lib.site-packages.pandas.tests.tslibs', 'venv.Lib.site-packages.pandas.tests.generic',
              'venv.Lib.site-packages.pandas.tests.groupby', 'venv.Lib.site-packages.pandas.tests.groupby.aggregate',
              'venv.Lib.site-packages.pandas.tests.indexes', 'venv.Lib.site-packages.pandas.tests.indexes.multi',
              'venv.Lib.site-packages.pandas.tests.indexes.period',
              'venv.Lib.site-packages.pandas.tests.indexes.interval',
              'venv.Lib.site-packages.pandas.tests.indexes.datetimes',
              'venv.Lib.site-packages.pandas.tests.indexes.timedeltas', 'venv.Lib.site-packages.pandas.tests.reshape',
              'venv.Lib.site-packages.pandas.tests.reshape.merge', 'venv.Lib.site-packages.pandas.tests.tseries',
              'venv.Lib.site-packages.pandas.tests.tseries.offsets', 'venv.Lib.site-packages.pandas.tests.indexing',
              'venv.Lib.site-packages.pandas.tests.indexing.interval',
              'venv.Lib.site-packages.pandas.tests.indexing.multiindex', 'venv.Lib.site-packages.pandas.tests.plotting',
              'venv.Lib.site-packages.pandas.tests.resample', 'venv.Lib.site-packages.pandas.tests.extension',
              'venv.Lib.site-packages.pandas.tests.extension.base',
              'venv.Lib.site-packages.pandas.tests.extension.json',
              'venv.Lib.site-packages.pandas.tests.extension.arrow',
              'venv.Lib.site-packages.pandas.tests.extension.numpy_',
              'venv.Lib.site-packages.pandas.tests.extension.decimal', 'venv.Lib.site-packages.pandas.tests.internals',
              'venv.Lib.site-packages.pandas.tests.arithmetic', 'venv.Lib.site-packages.pandas.tests.reductions',
              'venv.Lib.site-packages.pandas.tests.computation', 'venv.Lib.site-packages.pandas.arrays',
              'venv.Lib.site-packages.pandas.compat', 'venv.Lib.site-packages.pandas.compat.numpy',
              'venv.Lib.site-packages.pandas.errors', 'venv.Lib.site-packages.pandas.tseries',
              'venv.Lib.site-packages.pandas.plotting', 'venv.Lib.site-packages.pyasn1',
              'venv.Lib.site-packages.pyasn1.type', 'venv.Lib.site-packages.pyasn1.codec',
              'venv.Lib.site-packages.pyasn1.codec.ber', 'venv.Lib.site-packages.pyasn1.codec.cer',
              'venv.Lib.site-packages.pyasn1.codec.der', 'venv.Lib.site-packages.pyasn1.codec.native',
              'venv.Lib.site-packages.pyasn1.compat', 'venv.Lib.site-packages.tweepy', 'venv.Lib.site-packages.certifi',
              'venv.Lib.site-packages.chardet', 'venv.Lib.site-packages.chardet.cli', 'venv.Lib.site-packages.newsapi',
              'venv.Lib.site-packages.seaborn', 'venv.Lib.site-packages.seaborn.tests',
              'venv.Lib.site-packages.seaborn.colors', 'venv.Lib.site-packages.seaborn.external',
              'venv.Lib.site-packages.urllib3', 'venv.Lib.site-packages.urllib3.util',
              'venv.Lib.site-packages.urllib3.contrib', 'venv.Lib.site-packages.urllib3.contrib._securetransport',
              'venv.Lib.site-packages.urllib3.packages', 'venv.Lib.site-packages.urllib3.packages.backports',
              'venv.Lib.site-packages.urllib3.packages.ssl_match_hostname', 'venv.Lib.site-packages.dateutil',
              'venv.Lib.site-packages.dateutil.tz', 'venv.Lib.site-packages.dateutil.parser',
              'venv.Lib.site-packages.dateutil.zoneinfo', 'venv.Lib.site-packages.examples',
              'venv.Lib.site-packages.oauthlib', 'venv.Lib.site-packages.oauthlib.oauth1',
              'venv.Lib.site-packages.oauthlib.oauth1.rfc5849',
              'venv.Lib.site-packages.oauthlib.oauth1.rfc5849.endpoints', 'venv.Lib.site-packages.oauthlib.oauth2',
              'venv.Lib.site-packages.oauthlib.oauth2.rfc6749',
              'venv.Lib.site-packages.oauthlib.oauth2.rfc6749.clients',
              'venv.Lib.site-packages.oauthlib.oauth2.rfc6749.endpoints',
              'venv.Lib.site-packages.oauthlib.oauth2.rfc6749.grant_types', 'venv.Lib.site-packages.oauthlib.openid',
              'venv.Lib.site-packages.oauthlib.openid.connect', 'venv.Lib.site-packages.oauthlib.openid.connect.core',
              'venv.Lib.site-packages.oauthlib.openid.connect.core.endpoints',
              'venv.Lib.site-packages.oauthlib.openid.connect.core.grant_types', 'venv.Lib.site-packages.requests',
              'venv.Lib.site-packages.textblob', 'venv.Lib.site-packages.textblob.en',
              'venv.Lib.site-packages.textblob.unicodecsv', 'venv.Lib.site-packages.wordcloud',
              'venv.Lib.site-packages.cachetools', 'venv.Lib.site-packages.matplotlib',
              'venv.Lib.site-packages.matplotlib.tri', 'venv.Lib.site-packages.matplotlib.axes',
              'venv.Lib.site-packages.matplotlib.cbook', 'venv.Lib.site-packages.matplotlib.style',
              'venv.Lib.site-packages.matplotlib.compat', 'venv.Lib.site-packages.matplotlib.testing',
              'venv.Lib.site-packages.matplotlib.testing.jpl_units', 'venv.Lib.site-packages.matplotlib.backends',
              'venv.Lib.site-packages.matplotlib.backends.qt_editor', 'venv.Lib.site-packages.matplotlib.sphinxext',
              'venv.Lib.site-packages.matplotlib.projections', 'venv.Lib.site-packages.setuptools',
              'venv.Lib.site-packages.setuptools.extern', 'venv.Lib.site-packages.setuptools._vendor',
              'venv.Lib.site-packages.setuptools._vendor.packaging', 'venv.Lib.site-packages.setuptools.command',
              'venv.Lib.site-packages.mpl_toolkits.mplot3d', 'venv.Lib.site-packages.mpl_toolkits.axes_grid',
              'venv.Lib.site-packages.mpl_toolkits.axes_grid1', 'venv.Lib.site-packages.mpl_toolkits.axisartist',
              'venv.Lib.site-packages.pkg_resources', 'venv.Lib.site-packages.pkg_resources.extern',
              'venv.Lib.site-packages.pkg_resources._vendor', 'venv.Lib.site-packages.pkg_resources._vendor.packaging',
              'venv.Lib.site-packages.pyasn1_modules', 'venv.Lib.site-packages.requests_oauthlib',
              'venv.Lib.site-packages.requests_oauthlib.compliance_fixes'],
    url='',
    license='',
    author='ACER',
    author_email='',
    description=''
)
